/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Species = IDL.Variant({
  'other' : IDL.Null,
  'feline' : IDL.Null,
  'canine' : IDL.Null,
});
export const Sex = IDL.Variant({
  'female' : IDL.Null,
  'male' : IDL.Null,
  'femaleSpayed' : IDL.Null,
  'maleNeutered' : IDL.Null,
});
export const Time = IDL.Int;
export const Checklist = IDL.Record({
  'pdvmNotified' : IDL.Bool,
  'histo' : IDL.Bool,
  'labs' : IDL.Bool,
  'culture' : IDL.Bool,
  'surgeryReport' : IDL.Bool,
  'imaging' : IDL.Bool,
  'dischargeNotes' : IDL.Bool,
});
export const SurgeryCase = IDL.Record({
  'id' : IDL.Nat,
  'sex' : Sex,
  'arrivalDate' : Time,
  'presentingComplaint' : IDL.Text,
  'dateOfBirth' : IDL.Opt(Time),
  'medicalRecordNumber' : IDL.Text,
  'petName' : IDL.Text,
  'notes' : IDL.Text,
  'checklist' : Checklist,
  'ownerLastName' : IDL.Text,
  'breed' : IDL.Text,
  'species' : Species,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCase' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Species,
        IDL.Text,
        Sex,
        IDL.Opt(Time),
        IDL.Text,
        IDL.Text,
        Checklist,
      ],
      [SurgeryCase],
      [],
    ),
  'deleteCase' : IDL.Func([IDL.Nat], [], []),
  'getAllCases' : IDL.Func([], [IDL.Vec(SurgeryCase)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCase' : IDL.Func([IDL.Nat], [SurgeryCase], ['query']),
  'getCasesByOwner' : IDL.Func([IDL.Text], [IDL.Vec(SurgeryCase)], ['query']),
  'getChecklist' : IDL.Func([IDL.Nat], [Checklist], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchCasesByMedicalRecordNumber' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SurgeryCase)],
      ['query'],
    ),
  'updateCase' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Species,
        IDL.Text,
        Sex,
        IDL.Opt(Time),
        IDL.Text,
        IDL.Text,
        Checklist,
      ],
      [],
      [],
    ),
  'updateCaseNotes' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateChecklist' : IDL.Func([IDL.Nat, Checklist], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Species = IDL.Variant({
    'other' : IDL.Null,
    'feline' : IDL.Null,
    'canine' : IDL.Null,
  });
  const Sex = IDL.Variant({
    'female' : IDL.Null,
    'male' : IDL.Null,
    'femaleSpayed' : IDL.Null,
    'maleNeutered' : IDL.Null,
  });
  const Time = IDL.Int;
  const Checklist = IDL.Record({
    'pdvmNotified' : IDL.Bool,
    'histo' : IDL.Bool,
    'labs' : IDL.Bool,
    'culture' : IDL.Bool,
    'surgeryReport' : IDL.Bool,
    'imaging' : IDL.Bool,
    'dischargeNotes' : IDL.Bool,
  });
  const SurgeryCase = IDL.Record({
    'id' : IDL.Nat,
    'sex' : Sex,
    'arrivalDate' : Time,
    'presentingComplaint' : IDL.Text,
    'dateOfBirth' : IDL.Opt(Time),
    'medicalRecordNumber' : IDL.Text,
    'petName' : IDL.Text,
    'notes' : IDL.Text,
    'checklist' : Checklist,
    'ownerLastName' : IDL.Text,
    'breed' : IDL.Text,
    'species' : Species,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCase' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Species,
          IDL.Text,
          Sex,
          IDL.Opt(Time),
          IDL.Text,
          IDL.Text,
          Checklist,
        ],
        [SurgeryCase],
        [],
      ),
    'deleteCase' : IDL.Func([IDL.Nat], [], []),
    'getAllCases' : IDL.Func([], [IDL.Vec(SurgeryCase)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCase' : IDL.Func([IDL.Nat], [SurgeryCase], ['query']),
    'getCasesByOwner' : IDL.Func([IDL.Text], [IDL.Vec(SurgeryCase)], ['query']),
    'getChecklist' : IDL.Func([IDL.Nat], [Checklist], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchCasesByMedicalRecordNumber' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SurgeryCase)],
        ['query'],
      ),
    'updateCase' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Species,
          IDL.Text,
          Sex,
          IDL.Opt(Time),
          IDL.Text,
          IDL.Text,
          Checklist,
        ],
        [],
        [],
      ),
    'updateCaseNotes' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateChecklist' : IDL.Func([IDL.Nat, Checklist], [], []),
  });
};

export const init = ({ IDL }) => { return []; };