/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CompletedTasks {
  'pdvmNotified' : boolean,
  'histo' : boolean,
  'labs' : boolean,
  'culture' : boolean,
  'surgeryReport' : boolean,
  'imaging' : boolean,
  'dischargeNotes' : boolean,
}
export interface OpenAIConfig { 'initialized' : boolean, 'apiKey' : string }
export type Sex = { 'female' : null } |
  { 'male' : null } |
  { 'femaleSpayed' : null } |
  { 'maleNeutered' : null };
export type Species = { 'other' : null } |
  { 'feline' : null } |
  { 'canine' : null };
export interface SurgeryCase {
  'id' : bigint,
  'sex' : Sex,
  'arrivalDate' : Time,
  'completedTasks' : CompletedTasks,
  'presentingComplaint' : string,
  'dateOfBirth' : [] | [Time],
  'medicalRecordNumber' : string,
  'petName' : string,
  'notes' : string,
  'ownerLastName' : string,
  'breed' : string,
  'species' : Species,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCase' : ActorMethod<
    [
      string,
      Time,
      string,
      string,
      Species,
      string,
      Sex,
      [] | [Time],
      string,
      string,
      CompletedTasks,
    ],
    SurgeryCase
  >,
  'deleteCase' : ActorMethod<[bigint], undefined>,
  'getAllCases' : ActorMethod<[], Array<SurgeryCase>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCase' : ActorMethod<[bigint], SurgeryCase>,
  'getCaseByMedicalRecordNumber' : ActorMethod<[string], [] | [SurgeryCase]>,
  'getCasesByOwner' : ActorMethod<[string], Array<SurgeryCase>>,
  'getCompletedTasks' : ActorMethod<[bigint], CompletedTasks>,
  'getOpenAIConfig' : ActorMethod<[], [] | [OpenAIConfig]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCaseCreationAllowed' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchCasesByMedicalRecordNumber' : ActorMethod<
    [string],
    Array<SurgeryCase>
  >,
  'setOpenAIConfig' : ActorMethod<[string], undefined>,
  'updateCase' : ActorMethod<
    [
      bigint,
      string,
      Time,
      string,
      string,
      Species,
      string,
      Sex,
      [] | [Time],
      string,
      string,
      CompletedTasks,
    ],
    undefined
  >,
  'updateCaseNotes' : ActorMethod<[bigint, string], undefined>,
  'updateCompletedTasks' : ActorMethod<[bigint, CompletedTasks], undefined>,
  'validateOpenAIConfig' : ActorMethod<[], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];