/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Species = IDL.Variant({
  'other' : IDL.Null,
  'feline' : IDL.Null,
  'canine' : IDL.Null,
});
export const Sex = IDL.Variant({
  'female' : IDL.Null,
  'male' : IDL.Null,
  'femaleSpayed' : IDL.Null,
  'maleNeutered' : IDL.Null,
});
export const Task = IDL.Record({
  'cultureCompleted' : IDL.Bool,
  'cultureSelected' : IDL.Bool,
  'pdvmNotifiedCompleted' : IDL.Bool,
  'histoSelected' : IDL.Bool,
  'labsSelected' : IDL.Bool,
  'imagingCompleted' : IDL.Bool,
  'surgeryReportCompleted' : IDL.Bool,
  'imagingSelected' : IDL.Bool,
  'dischargeNotesCompleted' : IDL.Bool,
  'surgeryReportSelected' : IDL.Bool,
  'dischargeNotesSelected' : IDL.Bool,
  'histoCompleted' : IDL.Bool,
  'pdvmNotifiedSelected' : IDL.Bool,
  'labsCompleted' : IDL.Bool,
});
export const SurgeryCase = IDL.Record({
  'id' : IDL.Nat,
  'sex' : Sex,
  'arrivalDate' : Time,
  'presentingComplaint' : IDL.Text,
  'dateOfBirth' : IDL.Opt(Time),
  'task' : Task,
  'medicalRecordNumber' : IDL.Text,
  'petName' : IDL.Text,
  'notes' : IDL.Text,
  'ownerLastName' : IDL.Text,
  'breed' : IDL.Text,
  'species' : Species,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const OpenAIConfig = IDL.Record({
  'initialized' : IDL.Bool,
  'apiKey' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCase' : IDL.Func(
      [
        IDL.Text,
        Time,
        IDL.Text,
        IDL.Text,
        Species,
        IDL.Text,
        Sex,
        IDL.Opt(Time),
        IDL.Text,
        IDL.Text,
        Task,
      ],
      [SurgeryCase],
      [],
    ),
  'deleteCase' : IDL.Func([IDL.Nat], [], []),
  'getAllCases' : IDL.Func([], [IDL.Vec(SurgeryCase)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCase' : IDL.Func([IDL.Nat], [SurgeryCase], ['query']),
  'getCaseByMedicalRecordNumber' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SurgeryCase)],
      ['query'],
    ),
  'getCasesByOwner' : IDL.Func([IDL.Text], [IDL.Vec(SurgeryCase)], ['query']),
  'getOpenAIConfig' : IDL.Func([], [IDL.Opt(OpenAIConfig)], ['query']),
  'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCaseCreationAllowed' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchCasesByMedicalRecordNumber' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SurgeryCase)],
      ['query'],
    ),
  'setOpenAIConfig' : IDL.Func([IDL.Text], [], []),
  'updateCase' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        Time,
        IDL.Text,
        IDL.Text,
        Species,
        IDL.Text,
        Sex,
        IDL.Opt(Time),
        IDL.Text,
        IDL.Text,
        Task,
      ],
      [],
      [],
    ),
  'updateCaseNotes' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateTask' : IDL.Func([IDL.Nat, Task], [], []),
  'validateOpenAIConfig' : IDL.Func([], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Species = IDL.Variant({
    'other' : IDL.Null,
    'feline' : IDL.Null,
    'canine' : IDL.Null,
  });
  const Sex = IDL.Variant({
    'female' : IDL.Null,
    'male' : IDL.Null,
    'femaleSpayed' : IDL.Null,
    'maleNeutered' : IDL.Null,
  });
  const Task = IDL.Record({
    'cultureCompleted' : IDL.Bool,
    'cultureSelected' : IDL.Bool,
    'pdvmNotifiedCompleted' : IDL.Bool,
    'histoSelected' : IDL.Bool,
    'labsSelected' : IDL.Bool,
    'imagingCompleted' : IDL.Bool,
    'surgeryReportCompleted' : IDL.Bool,
    'imagingSelected' : IDL.Bool,
    'dischargeNotesCompleted' : IDL.Bool,
    'surgeryReportSelected' : IDL.Bool,
    'dischargeNotesSelected' : IDL.Bool,
    'histoCompleted' : IDL.Bool,
    'pdvmNotifiedSelected' : IDL.Bool,
    'labsCompleted' : IDL.Bool,
  });
  const SurgeryCase = IDL.Record({
    'id' : IDL.Nat,
    'sex' : Sex,
    'arrivalDate' : Time,
    'presentingComplaint' : IDL.Text,
    'dateOfBirth' : IDL.Opt(Time),
    'task' : Task,
    'medicalRecordNumber' : IDL.Text,
    'petName' : IDL.Text,
    'notes' : IDL.Text,
    'ownerLastName' : IDL.Text,
    'breed' : IDL.Text,
    'species' : Species,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const OpenAIConfig = IDL.Record({
    'initialized' : IDL.Bool,
    'apiKey' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCase' : IDL.Func(
        [
          IDL.Text,
          Time,
          IDL.Text,
          IDL.Text,
          Species,
          IDL.Text,
          Sex,
          IDL.Opt(Time),
          IDL.Text,
          IDL.Text,
          Task,
        ],
        [SurgeryCase],
        [],
      ),
    'deleteCase' : IDL.Func([IDL.Nat], [], []),
    'getAllCases' : IDL.Func([], [IDL.Vec(SurgeryCase)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCase' : IDL.Func([IDL.Nat], [SurgeryCase], ['query']),
    'getCaseByMedicalRecordNumber' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SurgeryCase)],
        ['query'],
      ),
    'getCasesByOwner' : IDL.Func([IDL.Text], [IDL.Vec(SurgeryCase)], ['query']),
    'getOpenAIConfig' : IDL.Func([], [IDL.Opt(OpenAIConfig)], ['query']),
    'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCaseCreationAllowed' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchCasesByMedicalRecordNumber' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SurgeryCase)],
        ['query'],
      ),
    'setOpenAIConfig' : IDL.Func([IDL.Text], [], []),
    'updateCase' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          Time,
          IDL.Text,
          IDL.Text,
          Species,
          IDL.Text,
          Sex,
          IDL.Opt(Time),
          IDL.Text,
          IDL.Text,
          Task,
        ],
        [],
        [],
      ),
    'updateCaseNotes' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateTask' : IDL.Func([IDL.Nat, Task], [], []),
    'validateOpenAIConfig' : IDL.Func([], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };